### ISSUE TITLE
Time refresh

### ISSUE THREAD

**Issue by carkillerpl** [PiotrMachowski/Home-Assistant-custom-components-Looko2#1]
What time refresh are set in plugin ? Actual look2 provider write to me that not offen that 20 minutes between asks of values per api key. othervise wilbe block by server.

**Comment by PiotrMachowski** [comment]
That's something new, there must have been a change in API usage conditions (I haven't received this email). I have to adjust code to limit a number of API calls.

**Comment by carkillerpl** [comment]
Tak mi napisali jak podali api  klucz.


Pozdrawiam

czw., 2 sty 2020, 01:15 użytkownik Piotr Machowski <notifications@github.com>
napisał:

**Comment by pprzybyl** [comment]
I have also requested the API key, and I also receive the same message. 
Waiting for update ;)

**Comment by ryrzy** [comment]
Jak wygląda sprawa Panowie z czasem odświeżania odczytu? po otrzymaniu tokena dostałem też info o minimalnym czasie 20 minut i nie chciałbym zablokować tokena :)

**Comment by PiotrMachowski** [comment]
In v1.0.1 I have limited an API usage with default interval of 20 min.
