### ISSUE TITLE
API serwer down

### ISSUE THREAD

**Issue by peetereczek** [PiotrMachowski/Home-Assistant-custom-components-Looko2#10]
API serwer seems down / unavailable. Integration is not working

**Comment by PiotrMachowski** [comment]
Server seems ok, maybe it's just your station?

**Comment by peetereczek** [comment]
Project page moved?
https://looko2web.nazwa.pl/aktualnosci/api/

![image](https://user-images.githubusercontent.com/42431204/192767757-2b5ce9dc-6eac-445f-9f26-64bbb21f9f28.png)

**Comment by peetereczek** [comment]
But anyway, you are right, sorry. Didn't thought that station can dissapear

> Server seems ok, maybe it's just your station?
