### ISSUE TITLE
Bład MySQLdb._exceptions.OperationalError

### ISSUE THREAD

**Issue by ryrzy** [PiotrMachowski/Home-Assistant-custom-components-Looko2#3]
Próbuję dodać sensor looko2 i w logu mam taki błąd (brak czujnika na liscie): 
`Szczegóły loga (ERROR)
Tue Feb 25 2020 08:11:23 GMT+0100 (czas środkowoeuropejski standardowy)
Error in database connectivity: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xC5\\x9B\\xC4\\x87 p...' for column `hass_log`.`states`.`state` at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.looko2_xx_1_ijpdescription', 'Jakość powietrza jest wciąż dobra. Zanieczyszczenia powietrza stanowią minimalne zagrożenie dla osób narażonych na ryzyko. Warunki bardzo dobre na aktywności na zewnątrz.', '{"friendly_name": "LookO2 xx\\u0142o\\u015bci 1 IJPDescription"}', xx, datetime.datetime(2020, 2, 25, 7, 10, 57, 920926, tzinfo=<UTC>), datetime.datetime(2020, 2, 25, 7, 10, 57, 920926, tzinfo=<UTC>), datetime.datetime(2020, 2, 25, 7, 11, 23, 322725), 'xx', None)]
(Background on this error at: http://sqlalche.me/e/e3q8). (retrying in 3 seconds)`

baza danych mariadb, tabele stworzył sobie HA sam, kodowanie tabel latin1_swedish_ci <- czy to jest problemem?

dziekuje

**Comment by ryrzy** [comment]
problem rozwiązany, nie był on spowodowany wtyczką, przepraszam za zamieszanie, wiecej info tutaj:

https://github.com/home-assistant/home-assistant/issues/31785

**Comment by PiotrMachowski** [comment]
Nie ma problemu, dzięki za podlinkowanie źródła
